### ISSUE TITLE
no timeout for poker command

### ISSUE THREAD

**Issue by FirezzzZ** [dragonfire535/xiao#60] opened 2020-05-25 14:57 UTC
![image](https://user-images.githubusercontent.com/55920870/82823885-f71f7000-9ec5-11ea-8c8f-ae103a74c867.png)

There's no timeout for this, its a continuos loop, also i think the winner part is never executed, please check the code

**Comment by FirezzzZ** [comment] 2020-05-25 14:59
im sure about the no timeout part, not sure about the winner part, we played for atleast 5-6 minutes but no winner

**Comment by FirezzzZ** [comment] 2020-05-25 15:00
![image](https://user-images.githubusercontent.com/55920870/82824154-6ac17d00-9ec6-11ea-9e62-7a728e2e5c7f.png)

the sentence `**${player.user}, I Couldn't Send Your Hand! Turn On DMs` is occuring as there was some error as this line is in the catch part and in the try part was this
`await player.user.send(stripIndents`
							**Your Poker Hand -**
							${player.hand.map(c => c.textDisplay).join('\n')}
							**Money -** $${formatNumber(player.money)}
							${bigBlind.id === player.id ? '_You Are The Big Blind!_' : ''}
							${smallBlind.id === player.id ? '_You Are The Small Blind!_' : ''}
						`);`

**Comment by dragonfire535** [comment] 2020-05-25 15:03
For the no timeout part, I can easily add a 10 second delay after games with no replies end. Though I'm not sure why you're using poker if no one is playing :V

As for the winner not being calculated, poker goes on until there's only one person with money left.

Finally, try turning on DMs to get rid of the "Couldn't send your hand!" message. The DM is failing to send.

**Comment by FirezzzZ** [comment] 2020-05-25 15:15
the turning on DMS part -
it was working perfectly, it had sent me some messages too and neither of our dms were off

**Comment by FirezzzZ** [comment] 2020-05-25 15:17
![image](https://user-images.githubusercontent.com/55920870/82825450-e4f30100-9ec8-11ea-9e81-e59d93e3e55f.png)

**Comment by dragonfire535** [comment] 2020-05-25 15:18
Can't reproduce the DM bug, must be on your end. As the other bug is fixed I will close this.

**Closed by dragonfire535** 2020-05-25 15:18 UTC
Labels: bug
