### ISSUE TITLE
Phone only sends messages to one channel if a channel is in two phone calls

### ISSUE THREAD

**Issue by FirezzzZ** [dragonfire535/xiao#53] opened 2020-05-18 10:59 UTC
So i recently was trying Your phone commands, they seem to be working fine when in 2 servers but when i try to use it in the 3rd server i can only send messages but cannot recieve them. Just wanted to know if it is natural or not!

**Comment by dragonfire535** [comment] 2020-05-18 15:56
It is unintended behavior for a channel to be in two phone calls at once. Currently working on a fix that prevents this.

**Comment by dragonfire535** [comment] 2020-05-18 15:58
Fixed in 9210ada744feaac8459f8e3bd8271bfca514da63

**Closed by dragonfire535** 2020-05-18 15:58 UTC
Labels: bug

**Comment by FirezzzZ** [comment] 2020-05-19 04:59
`const origin = bot.phone.find(call => call.origin.id === message.channel.id);`
{`bot.phone = new Collection()`)
when origin is console logged it is undefined if the message is sent from recipient to origin
but sends all details when message is sent from origin to recipient, i am confused because when i try to send message from origin, the message doesnt show in the recipient channel but when sent from recipient to origin, the messages show up in the origin channel. are you recieving the same error or its caused only by me.

**Comment by FirezzzZ** [comment] 2020-05-19 05:02
console logging thing is obvious why it comes undefined
but the second problem is confusing

**Comment by FirezzzZ** [comment] 2020-05-19 05:06
nvm it was error from my side only, ignore the messages. sorry
